name: $(BuildDefinitionName)-$(Rev:.rr)
trigger:
 - master
pr: none

jobs:
- job: Build
  strategy:
    matrix:
      Ubuntu:
        IMAGE_NAME: 'ubuntu-18.04'
        BIN_EXT: ''
      macOS:
        IMAGE_NAME: 'macOS-10.14'
        BIN_EXT: '.app'
      Windows:
        IMAGE_NAME: 'vs2017-win2016'
        BIN_EXT: '.exe'
  pool:
    vmImage: $(IMAGE_NAME)
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
    - bash: .azure-pipelines/build.sh
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: dist/start$(BIN_EXT)
        artifactName: angr-management-$(IMAGE_NAME)
