name: $(BuildDefinitionName)-$(Rev:.rr)
trigger:
 - master
pr: none

jobs:
- job: Build
  strategy:
    matrix:
      Ubuntu:
        IMAGE_NAME: 'ubuntu-18.04'
      macOS:
        IMAGE_NAME: 'macOS-10.14'
      Windows:
        IMAGE_NAME: 'windows-2019'
  pool:
    vmImage: $(IMAGE_NAME)
  steps:
    - bash: .azure-pipelines/build.sh
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: dist/start*
        artifactName: angr-management-$(IMAGE_NAME)
